[release] dev 작업 사항 release로 머지하기 2024-04-03 (2) (#45)
* [chore] yml 설정 수정 및 스키마 작성 (#1)

* rename: `application.properties` 파일 삭제

* chore: jpa 관련 yml 설정 변경

* chore: schema.sql 파일 작성

* [chore] 테스트 컨테이너 환경 구축 (#13)

* chore: `build.gradle`에 `testcontainer` 의존성 추가

* chore: 스키마에 스크립트 삭제

* 삭제를 안하면 테스트 컨테이너 작동 시 오류 발생

* chore: 테스트 실행 후 DB reset을 위한 sql 작성

* chore: `testcontainer` 환경 설정

* test: 인수 테스트를 위한 `AcceptanceTest` 클래스 구현

* [feat] 로그인 API 및 회원가입 로직 추가 (#9)

* feat: Member 관련 Entity 구현

* chore: Redis Session을 저장하기 위한 spring-session-data-redis 의존성 추가

* feat: 로그인 API 로직 구현

* feat: Member Entity에 NotNull 어노테이션 추가

* feat: AuthMemberService에 Transaction 어노테이션 추가

* rename: OAuthProvider 메서드명 authenticateAndFetchUserResource로 변경

* [feat] 로그인 로직에 GitHub OAuth 인증 추가 (#10)

* feat: 로그인 API 로직 구현

* feat: OAuth 로직을 위한 Properties 객체 추가

* feat: 로그인 Session Name을 위한 Properties 객체 추가 및 적용

* chore: 외부 API 요청을 위한 webflux 의존성 추가

* feat: GitHub OAuth 서버에 API 요청을 보내기 위한 WebClient Bean 등록

* feat: GitHub OAuth 인증 로직 추가

* docs: gitignore에 어플리케이션 YAML 설정 파일 추가

* rename: OAuthProvider 메서드명 authenticateAndFetchUserResource로 변경

* [feat] 로그아웃 API 구현 (#11)

* feat: 로그아웃 API 구현

* [feat] 로그인 상태를 검증해 주는 ArgumentResolver 구현 (#12)

* feat: 로그인 API 로직 구현

* feat: 로그아웃 API 구현

* feat: 로그인 상태를 검증해 주는 ArgumentResolver 구현

* rename: SessionMember 위치를 auth_member에서 global로 변경

* [feat] `Plan` 생성 기본 기능 구현  (#17)

* feat: Plan 관련 Entity 추가

* chore: schema.sql category table 명 plan_category로 변경

* feat: plan 생성 API 초안 구현

* feat: recurringOption dto 추가 및 plan 생성 검증 어노테이션 추가

* chore: `plan` 과 `recurring_option` null 옵션 변경

* feat: `Plan` 생성 기본 기능 구현

- title 기본값 설정 추가
- 반복 옵션 저장 추가

* style: 코드 자동 포맷팅

---------

Co-authored-by: Ju, Seonghwan (Ape) <crtevn@gmail.com>

* [feat] `Plan` 조회 및 삭제 기본 기능 구현 (#18)

* feat: Plan 관련 Entity 추가

* feat: plan 생성 API 초안 구현

* feat: `plan` 리스트 조회 구현

* feat: `Plan` 삭제 기본 구현

* chore: @Transactional 범위 수정 및 연관 엔티티 Lazy 로딩으로 변경

* feat: 조회 시 년도와 달 조건 추가

* feat: Plan 관련 Entity 추가

* feat: plan 생성 API 초안 구현

---------

Co-authored-by: Ju, Seonghwan (Ape) <crtevn@gmail.com>

* [feat] `PlanCategory` CRUD 기능 구현 (#14)

* feat: `PlanCategory` 생성 기능 구현

* feat: `PlanCategory` 조회 기능 구현

* feat: `PlanCategory` 삭제 기능 구현

* feat: `PlanCategory` 수정 기능 구현

* fix: `API` 스펙에 맞게 응답 `dto` 수정

* [test] `PlanCategory` CRUD 성공 케이스 테스트 코드 작성 (#15)

* test: `PlanCategory` 생성 요청 시 성공 응답 테스트 코드 작성

* test: `PlanCategory` 조회 요청 시 성공 응답 테스트 코드 작성

* test: `PlanCategory` 삭제 요청 시 성공 응답 테스트 코드 작성

* test: `PlanCategory` 수정 요청 시 성공 응답 테스트 코드 작성

* [feat] `Study` 생성 API 구현 (#28)

* feat: 시간을 필드로 갖는 `BaseEntity` 구현

* feat: `Study` 생성 API 구현

* feat: `Permission` & `Roll` 도메인 구현

* feat: 스터디 생성 시 리더의 `MemberStudy`가 생성되도록 로직 구현

* [refactor] `plan` 관련 피드백 반영 (#30)

* fix: `title` 공백 허용

* fix: `Plan` 조회 쿼리 수정

- `startTime` 또는 `endTime` 에만 해당 년,월이 포함되어도 조회되도록 수정

* refactor: pathVariable 이름 지정 삭제

* refactor: 서비스 레이어에서 도메인을 리턴하도록 변경

* refactor: @Transactional 위치 변경

* [chore] submodule 추가 (#21)

* chore: submodule 추가

* chore: 서브모듈에서 .yml 파일을 프로젝트 리소스로 자동 복사하는 Gradle Task 추

* [refactor] 로그인, 회원가입 관련 피드백 반영 (#20)

* refactor: `@CreationTimestamp` 대신 `@CreatedDate` 사용

- `@CreationTimestamp`은 hibernate 어노테이션, `@CreatedDate`은 spring data jpa 어노테이션 이다
- 이 프로젝트에선 spring data jpa을 메인으로 사용하므로 spring data jpa 어노테이션인 `@CreatedDate`를 사용하기로 함

* refactor: Member 생성자 접근제어자 public에서 private으로 변경

- 외부에서 호출할 일이 없으므로 기본 접근제어자를 private으로 한다

* refactor: Controller class 단위의 RequestMapping 어노테이션 제거

- 검색의 편의를 위해 메서드 단위에 API URL을 입력하도록 한다

* rename: Login -> SignIn으로 이름 변경

* rename: Converter 위치 infrastructure로 이동

* rename: SignInArgumentResolver 내부 변수명 더 명확하게 변경

* rename: OAuthProvider 관련 객체 패키지 auth_member로 이동

* rename: EnableConfigurationProperties 제거

* fix: 로그아웃 응답 상태 코드 204 No Content에서 200 OK로 변경

* rename: GitHubOAuthRequestException 패키지 위치 global에서 auth_member로 변경

* feat: Member 도메인에 TimeAuditingBaseEntity 적용

* [feat] GlobalExceptionHanlder 추가 요구 사항 구현 (#32)

* refactor: `@CreationTimestamp` 대신 `@CreatedDate` 사용

- `@CreationTimestamp`은 hibernate 어노테이션, `@CreatedDate`은 spring data jpa 어노테이션 이다
- 이 프로젝트에선 spring data jpa을 메인으로 사용하므로 spring data jpa 어노테이션인 `@CreatedDate`를 사용하기로 함

* feat: CustomException 추가

* feat: GeneralExceptionType 추가

* feat: GlobalExceptionHandler 추가

* feat: MemberExceptionType 추가 및 적용

* feat: AuthMemberExceptionType 추가 및 적용

* feat: AUTHENTICATION_FAILURE_EXCEPTION 적용

* rename: 예외 메서드명 컨벤션 대문자에서 카멜케이스로 변경

* [core] CORS 설정 추가 (#40)

* chore: Cors 설정 추가

* chore: EnableJpaAuditing 설정 중복 제거

* release: 첫 배포용 설정 파일 추가

* chore: .gitignore에 설정파일 경로 추가

* chore: .gitignore에 gradle/wrapper 경로 제거

* chore: gradle-wrapper.jar 추가

Git Action 실행 도중 Gradle build & push 작업에서 다음과 같은 에러가 발생하여 추가해 보기로 함

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
Error: Process completed with exit code 1.

---------

Co-authored-by: Lee Jee In <jinny.l.dev@gmail.com>
Co-authored-by: Dewey <115435482+jaea-kim@users.noreply.github.com>